import { ProductType } from "@/types/productTypes";

export const products: ProductType[] = [
  {
    name: "Chili Powder",
    weight: "100g",
    price: 2.10,
    category: "Spices",
    inStock: true,
  },
  {
    name: "Chicken Curry Powder",
    weight: "100g",
    price: 2.10,
    category: "Spices",
    inStock: true,
  },
  {
    name: "Curry Powder",
    weight: "100g",
    price: 2.10,
    category: "Spices",
    inStock: true,
  },
  {
    name: "Roasted Curry Powder",
    weight: "100g",
    price: 2.10,
    category: "Spices",
    inStock: true,
  },
  {
    name: "Chili Flex",
    weight: "100g",
    price: 2.10,
    category: "Spices",
    inStock: true,
  },
  {
    name: "Rampe",
    weight: "50g",
    price: 2.10,
    category: "Spices",
    inStock: true,
  },
  {
    name: "Karapincha",
    weight: "50g",
    price: 2.10,
    category: "Spices",
    inStock: true,
  },
  {
    name: "Maliban Gold Marie",
    weight: "80g",
    price: 1.90,
    category: "Biscuits",
    inStock: true,
  },
  {
    name: "Maliban Chocolate Biscuits",
    weight: "100g",
    price: 2.10,
    category: "Biscuits",
    inStock: true,
  },
  {
    name: "Munchee Cream Caker Super",
    weight: "125g",
    price: 2.20,
    category: "Biscuits",
    inStock: true,
  },
  {
    name: "Munchee Lemon Puff",
    weight: "100g",
    price: 2.10,
    category: "Biscuits",
    inStock: true,
  },
  {
    name: "Munchee Chocalate Puff",
    weight: "100g",
    price: 2.10,
    category: "Biscuits",
    inStock: true,
  },
  {
    name: "Munchee Hawainee Cookies",
    weight: "100g",
    price: 2.10,
    category: "Biscuits",
    inStock: true,
  },
  {
    name: "Samaposha",
    weight: "200g",
    price: 2.90,
    category: "Biscuits",
    inStock: true,
  },
  {
    name: "Chili Pastes",
    weight: "200g",
    price: 4.30,
    category: "Packaged Foods",
    inStock: true,
  },
  {
    name: "Male Achcharu",
    weight: "200g",
    price: 4.30,
    category: "Packaged Foods",
    inStock: true,
  },
  {
    name: "Brinjal Moju (Batumoju)",
    weight: "200g",
    price: 4.30,
    category: "Packaged Foods",
    inStock: true,
  },
  {
    name: "Fried Dried Sprats (Halmasso Badum)",
    weight: "200g",
    price: 4.30,
    category: "Packaged Foods",
    inStock: true,
  },
  {
    name: "Seeni Sambol",
    weight: "200g",
    price: 4.20,
    category: "Packaged Foods",
    inStock: true,
  },
  {
    name: "Coconut Sambol",
    weight: "200g",
    price: 4.20,
    category: "Packaged Foods",
    inStock: true,
  },
  {
    name: "Dry Sprats (Halmasso)",
    weight: "200g",
    price: 3.50,
    category: "Other Products",
    inStock: true,
  },
  {
    name: "Soya meat",
    weight: "90g",
    price: 2.10,
    category: "Other Products",
    inStock: true,
  },
  {
    name: "Red Rice",
    weight: "400g",
    price: 4.10,
    category: "Other Products",
    inStock: true,
  },
  {
    name: "Koththu Mee",
    weight: "80g",
    price: 1.90,
    category: "Other Products",
    inStock: true,
  },
  {
    name: "Raththi Milk Powder",
    weight: "200g",
    price: 3.90,
    category: "Other Products",
    inStock: true,
  },
  {
    name: "Milo",
    weight: "200g",
    price: 3.90,
    category: "Other Products",
    inStock: true,
  },
  {
    name: "Pol Toffe packets",
    weight: "175g",
    price: 2.50,
    category: "Other Products",
    inStock: true,
  },
  {
    name: "Mixer Bite",
    weight: "200g",
    price: 3.10,
    category: "Other Products",
    inStock: true,
  },
  {
    name: "EGB",
    weight: "250ml",
    price: 3.10,
    category: "Other Products",
    inStock: true,
  },
];
