import { ProductType } from "@/types/productTypes";

export const products: ProductType[] = [
  {
    name: "Chili Powder",
    weight: "100g",
    price: 2.0,
    category: "Spices",
    inStock: true,
  },
  {
    name: "Chicken Curry Powder",
    weight: "100g",
    price: 2.0,
    category: "Spices",
    inStock: true,
  },
  {
    name: "Curry Powder",
    weight: "50g",
    price: 1.5,
    category: "Spices",
    inStock: true,
  },
  {
    name: "Roasted Curry Powder",
    weight: "100g",
    price: 2.0,
    category: "Spices",
    inStock: true,
  },
  {
    name: "Chili Flex",
    weight: "100g",
    price: 2.0,
    category: "Spices",
    inStock: true,
  },
  {
    name: "Rampe",
    weight: "50g",
    price: 2.0,
    category: "Spices",
    inStock: true,
  },
  {
    name: "Karapincha",
    weight: "50g",
    price: 2.0,
    category: "Spices",
    inStock: true,
  },
  {
    name: "Maliban Gold Marie",
    weight: "100g",
    price: 1.9,
    category: "Biscuits",
    inStock: true,
  },
  {
    name: "Maliban Chocolate Biscuits",
    weight: "80g",
    price: 2.1,
    category: "Biscuits",
    inStock: true,
  },
  {
    name: "Munchee Cream Caker Super",
    weight: "125g",
    price: 2.2,
    category: "Biscuits",
    inStock: true,
  },
  {
    name: "Munchee Lemon Puff",
    weight: "100g",
    price: 2.1,
    category: "Biscuits",
    inStock: true,
  },
  {
    name: "Munchee Chocalate Puff",
    weight: "100g",
    price: 2.1,
    category: "Biscuits",
    inStock: true,
  },
  {
    name: "Munchee Hawainee Cookies",
    weight: "100g",
    price: 2.1,
    category: "Biscuits",
    inStock: true,
  },
  {
    name: "Samaposha",
    weight: "200g",
    price: 2.7,
    category: "Biscuits",
    inStock: true,
  },
  {
    name: "Chili pastes",
    weight: "200g",
    price: 4.2,
    category: "Other Products",
    inStock: true,
  },
  {
    name: "Male Achcharu",
    weight: "200g",
    price: 4.3,
    category: "Other Products",
    inStock: true,
  },
  {
    name: "Batumoju",
    weight: "200g",
    price: 4.3,
    category: "Other Products",
    inStock: true,
  },
  {
    name: "Halmasso badum",
    weight: "200g",
    price: 4.3,
    category: "Other Products",
    inStock: true,
  },
  {
    name: "Koththu Mee",
    weight: "80g",
    price: 1.9,
    category: "Other Products",
    inStock: true,
  },
  {
    name: "Soya meat",
    weight: "90g",
    price: 2.1,
    category: "Other Products",
    inStock: true,
  },
  {
    name: "Pol Toffe packets",
    weight: "175g",
    price: 2.3,
    category: "Other Products",
    inStock: true,
  },
  {
    name: "Milo",
    weight: "200g",
    price: 3.9,
    category: "Other Products",
    inStock: true,
  },
  {
    name: "Mixer Bite",
    weight: "200g",
    price: 3.0,
    category: "Other Products",
    inStock: true,
  },
];
